repos:
- hooks:
  - id: check-ast
  - args:
    - --fix=lf
    id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --max-line-length=120
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 6.1.0
- hooks:
  - id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
- hooks:
  - id: autoflake
  repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.10.0
- hooks:
  - id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
